spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shopDatabase?currentSchema=shop
    username: shop_admin
    password: shop_admin
  flyway:
    baseline-on-migrate: true