--USERS
DROP SEQUENCE IF EXISTS USER_SEQ;
CREATE SEQUENCE USER_SEQ START 1 INCREMENT 1;
DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE USERS
(
    ID        INT8    NOT NULL,
    NAME      VARCHAR(255),
    PASSWORD  VARCHAR(255),
    EMAIL     VARCHAR(255),
    PHONE     VARCHAR(255),
    ARCHIVE   BOOLEAN NOT NULL,
    ROLE      VARCHAR(255),
    BUCKET_ID INT8,
    PRIMARY KEY (ID)
);

--BUCKETS
DROP SEQUENCE IF EXISTS BUCKET_SEQ;
CREATE SEQUENCE BUCKET_SEQ START 1 INCREMENT 1;
DROP TABLE IF EXISTS BUCKETS CASCADE;
CREATE TABLE BUCKETS
(
    ID      INT8 NOT NULL,
    USER_ID INT8,
    PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS BUCKETS ADD CONSTRAINT BUCKETS_FK_USERS FOREIGN KEY (USER_ID) REFERENCES USERS;
ALTER TABLE IF EXISTS USERS ADD CONSTRAINT USERS_FK_BUCKETS FOREIGN KEY (BUCKET_ID) REFERENCES BUCKETS;

--CATEGORIES
DROP SEQUENCE IF EXISTS CATEGORY_SEQ;
CREATE SEQUENCE CATEGORY_SEQ START 1 INCREMENT 1;
DROP TABLE IF EXISTS CATEGORIES CASCADE;
CREATE TABLE CATEGORIES
(
    ID    INT8 NOT NULL,
    TITLE VARCHAR(255),
    PRIMARY KEY (ID)
);

--PRODUCTS
DROP SEQUENCE IF EXISTS PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ START 1 INCREMENT 1;
DROP TABLE IF EXISTS PRODUCTS CASCADE;
CREATE TABLE PRODUCTS
(
    ID    INT8 NOT NULL,
    TITLE VARCHAR(255),
    PRICE NUMERIC(19, 2),
    PRIMARY KEY (ID)
);

--PRODUCTS_CATEGORIES
DROP TABLE IF EXISTS PRODUCTS_CATEGORIES CASCADE;
CREATE TABLE PRODUCTS_CATEGORIES
(
    PRODUCT_ID  INT8 NOT NULL,
    CATEGORY_ID INT8 NOT NULL
);
ALTER TABLE IF EXISTS PRODUCTS_CATEGORIES ADD CONSTRAINT PRODUCTS_CATEGORIES_FK_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES;
ALTER TABLE IF EXISTS PRODUCTS_CATEGORIES ADD CONSTRAINT PRODUCTS_CATEGORIES_FK_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS;

--BUCKETS_PRODUCTS
DROP TABLE IF EXISTS BUCKETS_PRODUCTS CASCADE;
CREATE TABLE BUCKETS_PRODUCTS
(
    BUCKET_ID  INT8 NOT NULL,
    PRODUCT_ID INT8 NOT NULL
);
ALTER TABLE IF EXISTS BUCKETS_PRODUCTS ADD CONSTRAINT BUCKETS_PRODUCTS_FK_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS;
ALTER TABLE IF EXISTS BUCKETS_PRODUCTS ADD CONSTRAINT BUCKETS_PRODUCTS_FK_BUCKETS FOREIGN KEY (BUCKET_ID) REFERENCES BUCKETS;

--ORDERS
DROP SEQUENCE IF EXISTS ORDER_SEQ;
CREATE SEQUENCE ORDER_SEQ START 1 INCREMENT 1;
DROP TABLE IF EXISTS ORDERS CASCADE;
CREATE TABLE ORDERS
(
    ID      INT8 NOT NULL,
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    USER_ID INT8,
    SUM     NUMERIC(19, 2),
    ADDRESS VARCHAR(255),
    STATUS  VARCHAR(255),
    PRIMARY KEY (ID)
);
ALTER TABLE IF EXISTS ORDERS ADD CONSTRAINT ORDERS_FK_USERS FOREIGN KEY (USER_ID) REFERENCES USERS;

--ORDER_DETAILS
DROP SEQUENCE IF EXISTS ORDER_DETAILS_SEQ;
CREATE SEQUENCE ORDER_DETAILS_SEQ START 1 INCREMENT 1;
DROP TABLE IF EXISTS ORDER_DETAILS CASCADE;
CREATE TABLE ORDER_DETAILS
(
    ID         INT8 NOT NULL,
    AMOUNT     NUMERIC(19, 2),
    PRICE      NUMERIC(19, 2),
    ORDER_ID   INT8,
    PRODUCT_ID INT8,
    PRIMARY KEY (ID)
);
ALTER TABLE IF EXISTS ORDER_DETAILS ADD CONSTRAINT ORDER_DETAILS_FK_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS;
ALTER TABLE IF EXISTS ORDER_DETAILS ADD CONSTRAINT ORDER_DETAILS_FK_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS;

--ORDERS_DETAILS
DROP TABLE IF EXISTS ORDERS_DETAILS CASCADE;
CREATE TABLE ORDERS_DETAILS
(
    ORDER_ID   INT8 NOT NULL,
    DETAILS_ID INT8 NOT NULL
);
ALTER TABLE IF EXISTS ORDERS_DETAILS ADD CONSTRAINT UK_ORDERS_DETAILS UNIQUE (DETAILS_ID);
ALTER TABLE IF EXISTS ORDERS_DETAILS ADD CONSTRAINT ORDERS_DETAILS_FK_ORDER_DETAILS FOREIGN KEY (DETAILS_ID) REFERENCES ORDER_DETAILS;
ALTER TABLE IF EXISTS ORDERS_DETAILS ADD CONSTRAINT ORDERS_DETAILS_FK_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS;